/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module HalfAdderAdd (
  input X,
  input Y,
  output S,
  output C
);
  assign S = (X ^ Y);
  assign C = (X & Y);
endmodule
